external-user-service:
  ribbon:
    listOfServers: ${USER-SERVICE-URL}
external-front-end-service:
  ribbon:
    listOfServers: ${FRONT-END-SERVICE-URL}
eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com