external-user-service:
  ribbon:
    listOfServers: ${USER-SERVICE-URL:http://localhost:8888}
external-front-end-service:
  ribbon:
    listOfServers: ${FRONT-END-SERVICE-URL:http://localhost:8081}
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}